// all_qs/06.Cultural_and_Moral_Challenges/q059.js
export default {
  question: "What does Christianity say about slavery?",
  answer: `Christianity teaches that all people are created equal in the image of God and possess inherent dignity and worth. While the Bible addresses slavery as it existed in the ancient world, the core message of Scripture emphasizes human freedom, justice, and the equal value of every person before God. Galatians 3:28 declares, "There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus." This revolutionary teaching laid the foundation for the eventual abolition of slavery and continues to call Christians to fight injustice wherever it exists today.

**1. Biblical Slavery Was Debt Bondage and War Captivity, Not Chattel Slavery**
The slavery mentioned in the Bible was fundamentally different from the brutal chattel slavery of more recent history. In the ancient world, slavery took several forms:

  •	*Debt Bondage* was a temporary arrangement where people would work to pay off debts or provide for themselves during hardship. Under Mosaic Law, Hebrew servants were to be released after six years. Exodus 21:2 states, "If you buy a Hebrew servant, he is to serve you for six years. But in the seventh year, he shall go free, without paying anything." Additionally, every 50 years during the Year of Jubilee, all debts were cancelled and servants were freed. Leviticus 25:10 declares, "Consecrate the fiftieth year and proclaim liberty throughout the land to all its inhabitants. It shall be a jubilee for you; each of you is to return to your family property and to your own clan."
  •	*War Captives* were also taken as servants in ancient times. In a world of constant tribal warfare, this practice served to prevent ongoing rebellion and bloodshed. Rather than executing defeated enemies or leaving them to starve, they were integrated into the community as servants. However, even these captives had legal protections under Mosaic Law and were to be treated humanely.

The Law provided protections for all servants: they had the right to rest on the Sabbath. Exodus 20:10 commands, "But the seventh day is a sabbath to the LORD your God. On it you shall not do any work, neither you, nor your son or daughter, nor your male or female servant." Furthermore, if a master injured a servant, the servant was to go free. Exodus 21:26-27 states, "An owner who hits a male or female slave in the eye and destroys it must let the slave go free to compensate for the eye. And an owner who knocks out the tooth of a male or female slave must let the slave go free to compensate for the tooth." This system was not based on race or the idea that some people were property to be owned permanently. It included pathways to freedom and dignity that were revolutionary for the ancient world.

**2. God Is a Liberator: The Exodus Story**
At the very heart of the biblical narrative is the story of God freeing the Israelites from slavery in Egypt. The Exodus is one of the most important events in Scripture, demonstrating God's character as a liberator who hears the cries of the oppressed. Exodus 3:7-8 records God saying to Moses: "I have indeed seen the misery of my people in Egypt. I have heard them crying out because of their slave drivers, and I am concerned about their suffering. So I have come down to rescue them." God didn't tolerate the brutal enslavement of His people; He actively intervened to set them free. Throughout the Old Testament, God repeatedly reminds Israel, "Remember that you were slaves in Egypt and the LORD your God redeemed you" (Deuteronomy 15:15). This memory was meant to shape how they treated others, especially the vulnerable and marginalized. The Exodus reveals God's heart for freedom and justice. It establishes a pattern throughout Scripture: God sides with the oppressed and calls His people to do the same. This foundational story makes clear that God opposes the kind of dehumanizing, permanent, race-based slavery that later emerged in history.

**3. The Gospel Message Undermined Slavery**
The New Testament did not explicitly call for the immediate abolition of slavery in the Roman Empire, doing so would have been politically impossible and likely led to violent suppression. However, the teachings of Jesus and the apostles planted seeds that would eventually dismantle the institution. Paul's letter to Philemon is a powerful example. Paul sent the runaway slave Onesimus back to his master Philemon, but urged Philemon to receive him "no longer as a slave, but better than a slave, as a dear brother" (Philemon 1:16). Paul was transforming the relationship from ownership to brotherhood in Christ. Similarly, Paul wrote, "Masters, provide your slaves with what is right and fair, because you know that you also have a Master in heaven" (Colossians 4:1), reminding slave owners that they too were accountable to God and must treat others justly.
  The gospel message that all are equal before God and that Christ died for all people regardless of social status fundamentally challenged the dehumanization required to sustain slavery.

**4. Christianity Led the Fight to Abolish Slavery**
Throughout history, committed Christians were at the forefront of the abolitionist movement. In Britain, William Wilberforce, a devout evangelical Christian, spent decades campaigning in Parliament to end the slave trade, finally succeeding with the Slave Trade Act of 1807 and the Slavery Abolition Act of 1833. He was motivated by his faith and the conviction that slavery was a sin against God.
  In America, many abolitionists were Christians who saw slavery as incompatible with biblical teaching. Harriet Beecher Stowe's Uncle Tom's Cabin, which galvanized anti-slavery sentiment, was written from a Christian perspective. Churches and Christian organizations formed the backbone of the Underground Railroad, risking their lives to help enslaved people escape to freedom.
  These believers understood that the biblical principles of justice, mercy, and love for neighbour (Micah 6:8, Matthew 22:39) demanded the end of slavery. They recognized that the image of God in every person (Genesis 1:27) made the ownership and brutalization of human beings morally indefensible. They drew inspiration from the Exodus story, seeing themselves as continuing God's work of liberation.

**5. Some Twisted Scripture to Justify Slavery**
Tragically, there were those who misused and corrupted biblical texts to defend slavery, particularly in the American South. They selectively quoted passages out of context, ignored the broader biblical narrative of liberation and justice exemplified in the Exodus, and twisted Scripture to serve economic and social interests rather than God's truth.
  This abuse of the Bible does not reflect authentic Christian teaching. Jesus condemned those who distorted God's Word for their own purposes. In Matthew 15:6-9, He rebuked the religious leaders: "Thus you nullify the word of God for the sake of your tradition. You hypocrites! Isaiah was right when he prophesied about you: 'These people honour me with their lips, but their hearts are far from me. They worship me in vain; their teachings are merely human rules.'" The misuse of Scripture to oppress others is a grave sin, and it stands in direct opposition to the heart of the gospel, which proclaims freedom, justice, and the equal worth of all people. As 2 Peter 3:16 warns, some "distort" the Scriptures "to their own destruction."

**6. Slavery Still Exists Today**
While legal chattel slavery has been abolished in most of the world, modern slavery persists in various forms. According to global estimates, over 40 million people are trapped in forced labour, human trafficking, debt bondage, and sexual exploitation today. This includes children forced to work in dangerous conditions, women and girls trafficked for prostitution, and workers held in servitude through threats and violence.
Christians are called to continue the fight against these injustices. Proverbs 31:8-9 commands, "Speak up for those who cannot speak for themselves, for the rights of all who are destitute. Speak up and judge fairly; defend the rights of the poor and needy." The same biblical principles that drove the abolition movement in the past, rooted in the Exodus story of God liberating the oppressed, compel believers today to advocate for the oppressed, support anti-trafficking organizations, and work toward a world where every person experiences the freedom and dignity God intends.

Christianity teaches that slavery, both ancient and modern, is incompatible with the biblical vision of human dignity and equality. The Exodus story reveals God's heart as a liberator who frees the oppressed, and this theme runs throughout Scripture. While the Bible addressed the realities of the ancient world, including debt bondage and war captivity, its core message of liberation, justice, and the image of God in every person laid the groundwork for abolition. Christians led the charge to end slavery historically, even as some tragically twisted Scripture to defend it. Today, believers are called to continue fighting modern slavery in all its forms, upholding the truth that every person is created in God's image and deserves freedom, justice, and compassion.`
};